export const EXCLUDES = [
  "CYBER",
  "SIAM SHAME",
  "There For Tomorrow",
  "Artificial Language",
  "Children Of Bodom",
  "Breakdown of Sanity",
  "Uchu Conbini",
  "sora tob sakana",
  "Seiko Matsuda",
  "Cynic",
  "The Afterimage",
  "Euphoreon",
  "JUDY AND MARY",
  "Ever Forthright",
  "桃箱",
  "Happy Kuru Kuru",
  "BILLIE IDLE",
  "YVR",
];
